---
:name: Set Me Free
:price: "£17.46"
:description: Aaron Ledbetter’s future had been planned out for him since before he
  was born. Each year, the Ledbetter family vacation on Tybee Island gave Aaron a
  chance to briefly free himself from his family’s expectations. When he meets Jonas
  “Lucky” Luckett, a caricature artist in town with the traveling carnival, he must
  choose between the life that’s been mapped out for him, and Aaron Ledbetter’s future
  had been planned out for him since before he was born. Each year, the Ledbetter
  family vacation on Tybee Island gave Aaron a chance to briefly free himself from
  his family’s expectations. When he meets Jonas “Lucky” Luckett, a caricature artist
  in town with the traveling carnival, he must choose between the life that’s been
  mapped out for him, and the chance at true love. ...more
:category: Young Adult
:image_path: media_dir/Young Adult/set_me_free.jpg
